// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1zgHnNuL_33B_sVDx_KFwiylaYLkjFAI',
    appId: '1:672025139128:web:ad25f917eabeb7741e214d',
    messagingSenderId: '672025139128',
    projectId: 'fruitapp-ec962',
    authDomain: 'fruitapp-ec962.firebaseapp.com',
    storageBucket: 'fruitapp-ec962.firebasestorage.app',
    measurementId: 'G-YTFHXEWSRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zCR5QERvzTKpMelqgcNAf57ei2JV4f0',
    appId: '1:672025139128:android:242a7b6e194e26b71e214d',
    messagingSenderId: '672025139128',
    projectId: 'fruitapp-ec962',
    storageBucket: 'fruitapp-ec962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6wNmRxEN9xziyVQUdxE2Ku2Fn32UXDM8',
    appId: '1:672025139128:ios:de62d51867a16f2a1e214d',
    messagingSenderId: '672025139128',
    projectId: 'fruitapp-ec962',
    storageBucket: 'fruitapp-ec962.firebasestorage.app',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6wNmRxEN9xziyVQUdxE2Ku2Fn32UXDM8',
    appId: '1:672025139128:ios:de62d51867a16f2a1e214d',
    messagingSenderId: '672025139128',
    projectId: 'fruitapp-ec962',
    storageBucket: 'fruitapp-ec962.firebasestorage.app',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1zgHnNuL_33B_sVDx_KFwiylaYLkjFAI',
    appId: '1:672025139128:web:417c0b8dc0d8b5e51e214d',
    messagingSenderId: '672025139128',
    projectId: 'fruitapp-ec962',
    authDomain: 'fruitapp-ec962.firebaseapp.com',
    storageBucket: 'fruitapp-ec962.firebasestorage.app',
    measurementId: 'G-XT5BBHJL6M',
  );

}